INSERT INTO category VALUES (1, 'Кольца');
INSERT INTO category VALUES (2, 'Ожерелья');
INSERT INTO category VALUES (3, 'Серьги');
INSERT INTO category VALUES (4, 'Браслеты');
INSERT INTO category VALUES (5, 'Колье');
INSERT INTO category VALUES (6, 'Комплекты');

INSERT INTO post VALUES (1, 1, 'Супер кольцо баюма', 199);
INSERT INTO post VALUES (2, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (3, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (4, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (5, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (6, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (7, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (8, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (9, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (10, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (11, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (12, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (13, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (14, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (15, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (16, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (17, 1, 'Супер кольцо королевы муравьев', 99);
INSERT INTO post VALUES (18, 1, 'Супер кольцо королевы муравьев', 99);